Addes postgres 13.2-alpine db service and config
MSF-OCB/orthanc-docker pull request #2
Opened 2021-04-13 13:42 UTC by sverachimsf

modifed docker-compose.yml and arthenc.json

added postgres db service with minor version 13.2 and linux alpine distr image
used image osimis/orthanc which corresponds to jodogne/orthanc-plugins:1.9.1

2021-04-14 14:24 UTC, R-VdP requested changes

2021-04-14 14:24 UTC, R-VdP commented on docker-compose.yml
> -    hostname: orthanc
Can we keep the container_name and hostname properties? Those are very useful.

2021-04-14 14:24 UTC, R-VdP commented on docker-compose.yml
> +    depends_on: [orthanc-pg]
No need for the brackets, this might confuse people who are not that knowledgeable about YAML syntax.
You can just write:
```yml
depends_on:
  - orthanc-pg
```

2021-04-14 14:24 UTC, R-VdP commented on orthanc.json
> +    "Password" :  "%postgres_password%",
How does this work exactly? I do not see this syntax documented anywhere. Is this the literal password or is this a placeholder that will be replaced somehow? Or can we remove it given that we already set the password in the docker-compose file?

2021-04-14 15:13 UTC, sverachimsf commented on docker-compose.yml
> -    hostname: orthanc
Ok I will put again these params; I don't think it will impact

2021-04-14 15:13 UTC, sverachimsf commented on docker-compose.yml
> +    depends_on: [orthanc-pg]
ok

2021-04-14 15:18 UTC, sverachimsf commented on orthanc.json
> +    "Password" :  "%postgres_password%",
A varible that can be replaced, a placeholder with value store in .env. Like in lines 162 - 166 where the password is stored in .env

162  // The list of the registered users. Because Orthanc uses HTTP
163 // Basic Authentication, the passwords are stored as plain text.
164  "RegisteredUsers" : {
165    "msfocb" : "%orthanc_http_password%"
 166 },

2021-04-14 15:32 UTC, R-VdP commented on orthanc.json
> +    "Password" :  "%postgres_password%",
Ah, but then you'll need to adapt the entrypoint script, this is something that I wrote:
https://github.com/MSF-OCB/orthanc-docker/blob/master/entrypoint.sh

In this case, we can just use the env var "ORTHANC__POSTGRESQL__PASSWORD" though, no need to do any replacements ourselves.
I think we can do the same thing for the HTTP password, I didn't know that this functionality existed when I wrote this.

2021-04-15 10:00 UTC, sverachimsf commented on orthanc.json
> +    "Password" :  "%postgres_password%",
I was actually assigning the orthanc_http_password value to POSTGRES_PASSWORD but actully better not use replacment and use directly this environment variable ORTHANC__POSTGRESQL__PASSWORD ... ok I will do that

2021-04-15 10:03 UTC, sverachimsf commented on orthanc.json
> +    "Password" :  "%postgres_password%",
enev though using ORTHANC__POSTGRESQL__PASSWORD implies secrets and Docker Swarm or Kubernetes environment ...
so not sure if with docker-compose it will work, to be checked

2021-04-16 12:27 UTC, closed without merging

2021-04-16 12:27 UTC, R-VdP commented
See #3.